"""
Schema defining all customizable keyboard shortcuts.
Maps config keys to human-readable labels for the settings UI.
"""
# Format: (config_key, display_label)
SHORTCUT_SCHEMA = [
    ("open", "Open File"),
    ("close", "Close File"),
    ("save", "Save"),
    ("save_as", "Save As"),
    ("save_to", "Change Output Dir"),
    ("quit", "Quit"),
    ("delete_file", "Delete File"),
    ("open_prev", "Previous Slice"),
    ("open_next", "Next Slice"),
    ("zoom_in", "Zoom In"),
    ("zoom_out", "Zoom Out"),
    ("zoom_to_original", "Zoom To Original"),
    ("fit_window", "Fit Window"),
    ("fit_width", "Fit Width"),
    ("create_rectangle", "Create Rectangle (polygon)"),
    ("create_point", "Create Point"),
    ("create_brush_mode", "Brush Mode (uses mask ID under cursor)"),
    ("create_ai_mask_mode", "Points AI-Mask"),
    ("create_ai_boundary_mode", "AI Boundary"),
    ("create_watershed_3d_mode", "Watershed Seeds"),
    ("select_mode", "View / Select"),
    ("escape", "Escape (clear points / select mode)"),
    ("toggle_keep_prev_mode", "Keep Previous Annotation"),
    ("undo", "Undo"),
    ("redo", "Redo"),
    ("undo_last_point", "Undo Last Point"),
    ("view_axis_axial", "Axial View (Ctrl+A)"),
    ("view_axis_coronal", "Coronal View (Ctrl+C)"),
    ("view_axis_sagittal", "Sagittal View (Ctrl+S)"),
    ("verify_label", "Verify (Finalize) Label"),
    ("revert_label", "Revert Label to Proposed"),
    ("reject_label", "Reject (Delete) Label"),
    ("commit", "Commit Changes"),
    ("hide_verified", "Toggle Hide Verified"),
    ("solo_label", "Solo Current Label"),
    ("show_all_labels", "Show All Labels"),
    ("focus_label_search", "Focus Label Search"),
    ("focus_brush_label", "Focus Brush Label Input"),
    ("set_brush_label_0", "Set Brush Label to 0"),
    ("toggle_3d", "Toggle 3D View"),
]
